# Generated by Django 6.0.7 on 2026-07-22 01:13

from django.db import migrations, models


def renombrar_pendiente_a_pendiente_pago(apps, schema_editor):
    """Los pedidos que ya existían con estado='pendiente' (nombre viejo)
    pasan a 'pendiente_pago' (nombre nuevo), para que sigan reconociéndose
    en las validaciones de flujo de PedidoViewSet."""
    Pedido = apps.get_model('api', 'Pedido')
    Pedido.objects.filter(estado='pendiente').update(estado='pendiente_pago')


def revertir_pendiente_pago_a_pendiente(apps, schema_editor):
    Pedido = apps.get_model('api', 'Pedido')
    Pedido.objects.filter(estado='pendiente_pago').update(estado='pendiente')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_direccion_pedido_direccion_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('deposito', 'Depósito bancario'), ('tarjeta', 'Tarjeta')], default='deposito', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente_pago', max_length=20),
        ),
        migrations.RunPython(renombrar_pendiente_a_pendiente_pago, revertir_pendiente_pago_a_pendiente),
    ]
