# Generated by Django 6.0.7 on 2026-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pedido_metodo_pago_pedido_motivo_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
