# Generated by Django 6.0.7 on 2026-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_preguntaproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.URLField(max_length=500),
        ),
    ]
